global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: 'sinaps_api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: /metrics

  - job_name: 'system'
    static_configs:
      - targets: ['node_exporter:9100']

storage:
  tsdb:
    retention:
      time: 15d

